# Generated by Django 3.0.3 on 2020-02-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200224_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='name',
            field=models.CharField(default='name', max_length=256),
            preserve_default=False,
        ),
    ]
