# Generated by Django 3.0.3 on 2020-02-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_history_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='name',
        ),
    ]
